/*
 * This file is generated by jOOQ.
 */
package com.ymm.back.domain.tables.daos;


import com.ymm.back.domain.tables.Databasechangelog;
import com.ymm.back.domain.tables.records.DatabasechangelogRecord;

import java.time.LocalDateTime;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DatabasechangelogDao extends DAOImpl<DatabasechangelogRecord, com.ymm.back.domain.tables.pojos.Databasechangelog, Integer> {

    /**
     * Create a new DatabasechangelogDao without any configuration
     */
    public DatabasechangelogDao() {
        super(Databasechangelog.DATABASECHANGELOG, com.ymm.back.domain.tables.pojos.Databasechangelog.class);
    }

    /**
     * Create a new DatabasechangelogDao with an attached configuration
     */
    public DatabasechangelogDao(Configuration configuration) {
        super(Databasechangelog.DATABASECHANGELOG, com.ymm.back.domain.tables.pojos.Databasechangelog.class, configuration);
    }

    @Override
    public Integer getId(com.ymm.back.domain.tables.pojos.Databasechangelog object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>create_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.ymm.back.domain.tables.pojos.Databasechangelog> fetchRangeOfCreateTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Databasechangelog.DATABASECHANGELOG.CREATE_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.ymm.back.domain.tables.pojos.Databasechangelog> fetchByCreateTime(LocalDateTime... values) {
        return fetch(Databasechangelog.DATABASECHANGELOG.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>update_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.ymm.back.domain.tables.pojos.Databasechangelog> fetchRangeOfUpdateTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Databasechangelog.DATABASECHANGELOG.UPDATE_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>update_time IN (values)</code>
     */
    public List<com.ymm.back.domain.tables.pojos.Databasechangelog> fetchByUpdateTime(LocalDateTime... values) {
        return fetch(Databasechangelog.DATABASECHANGELOG.UPDATE_TIME, values);
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.ymm.back.domain.tables.pojos.Databasechangelog> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Databasechangelog.DATABASECHANGELOG.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.ymm.back.domain.tables.pojos.Databasechangelog> fetchById(Integer... values) {
        return fetch(Databasechangelog.DATABASECHANGELOG.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.ymm.back.domain.tables.pojos.Databasechangelog fetchOneById(Integer value) {
        return fetchOne(Databasechangelog.DATABASECHANGELOG.ID, value);
    }
}
