/*
 * This file is generated by jOOQ.
 */
package com.ymm.back.domain.tables.daos;


import com.ymm.back.domain.tables.FileStorage;
import com.ymm.back.domain.tables.records.FileStorageRecord;

import java.time.LocalDateTime;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FileStorageDao extends DAOImpl<FileStorageRecord, com.ymm.back.domain.tables.pojos.FileStorage, Integer> {

    /**
     * Create a new FileStorageDao without any configuration
     */
    public FileStorageDao() {
        super(FileStorage.FILE_STORAGE, com.ymm.back.domain.tables.pojos.FileStorage.class);
    }

    /**
     * Create a new FileStorageDao with an attached configuration
     */
    public FileStorageDao(Configuration configuration) {
        super(FileStorage.FILE_STORAGE, com.ymm.back.domain.tables.pojos.FileStorage.class, configuration);
    }

    @Override
    public Integer getId(com.ymm.back.domain.tables.pojos.FileStorage object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.ymm.back.domain.tables.pojos.FileStorage> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(FileStorage.FILE_STORAGE.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.ymm.back.domain.tables.pojos.FileStorage> fetchById(Integer... values) {
        return fetch(FileStorage.FILE_STORAGE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.ymm.back.domain.tables.pojos.FileStorage fetchOneById(Integer value) {
        return fetchOne(FileStorage.FILE_STORAGE.ID, value);
    }

    /**
     * Fetch records that have <code>message_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.ymm.back.domain.tables.pojos.FileStorage> fetchRangeOfMessageId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(FileStorage.FILE_STORAGE.MESSAGE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>message_id IN (values)</code>
     */
    public List<com.ymm.back.domain.tables.pojos.FileStorage> fetchByMessageId(Integer... values) {
        return fetch(FileStorage.FILE_STORAGE.MESSAGE_ID, values);
    }

    /**
     * Fetch records that have <code>url BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.ymm.back.domain.tables.pojos.FileStorage> fetchRangeOfUrl(String lowerInclusive, String upperInclusive) {
        return fetchRange(FileStorage.FILE_STORAGE.URL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>url IN (values)</code>
     */
    public List<com.ymm.back.domain.tables.pojos.FileStorage> fetchByUrl(String... values) {
        return fetch(FileStorage.FILE_STORAGE.URL, values);
    }

    /**
     * Fetch records that have <code>filename BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.ymm.back.domain.tables.pojos.FileStorage> fetchRangeOfFilename(String lowerInclusive, String upperInclusive) {
        return fetchRange(FileStorage.FILE_STORAGE.FILENAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>filename IN (values)</code>
     */
    public List<com.ymm.back.domain.tables.pojos.FileStorage> fetchByFilename(String... values) {
        return fetch(FileStorage.FILE_STORAGE.FILENAME, values);
    }

    /**
     * Fetch records that have <code>create_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.ymm.back.domain.tables.pojos.FileStorage> fetchRangeOfCreateTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(FileStorage.FILE_STORAGE.CREATE_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.ymm.back.domain.tables.pojos.FileStorage> fetchByCreateTime(LocalDateTime... values) {
        return fetch(FileStorage.FILE_STORAGE.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>update_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.ymm.back.domain.tables.pojos.FileStorage> fetchRangeOfUpdateTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(FileStorage.FILE_STORAGE.UPDATE_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>update_time IN (values)</code>
     */
    public List<com.ymm.back.domain.tables.pojos.FileStorage> fetchByUpdateTime(LocalDateTime... values) {
        return fetch(FileStorage.FILE_STORAGE.UPDATE_TIME, values);
    }
}
