/*
 * This file is generated by jOOQ.
 */
package com.ymm.back.domain.tables.records;


import com.ymm.back.domain.tables.Agenda;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AgendaRecord extends UpdatableRecordImpl<AgendaRecord> implements Record11<Integer, Integer, Integer, LocalDateTime, LocalDateTime, String, String, LocalDateTime, String, String, String> {

    private static final long serialVersionUID = 1057286640;

    /**
     * Setter for <code>agenda.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>agenda.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>agenda.member_id</code>.
     */
    public void setMemberId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>agenda.member_id</code>.
     */
    public Integer getMemberId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>agenda.project_id</code>.
     */
    public void setProjectId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>agenda.project_id</code>.
     */
    public Integer getProjectId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>agenda.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>agenda.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>agenda.update_time</code>.
     */
    public void setUpdateTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>agenda.update_time</code>.
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>agenda.name</code>.
     */
    public void setName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>agenda.name</code>.
     */
    public String getName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>agenda.description</code>.
     */
    public void setDescription(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>agenda.description</code>.
     */
    public String getDescription() {
        return (String) get(6);
    }

    /**
     * Setter for <code>agenda.finish_time</code>.
     */
    public void setFinishTime(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>agenda.finish_time</code>.
     */
    public LocalDateTime getFinishTime() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>agenda.result</code>.
     */
    public void setResult(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>agenda.result</code>.
     */
    public String getResult() {
        return (String) get(8);
    }

    /**
     * Setter for <code>agenda.status</code>.
     */
    public void setStatus(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>agenda.status</code>.
     */
    public String getStatus() {
        return (String) get(9);
    }

    /**
     * Setter for <code>agenda.item</code>.
     */
    public void setItem(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>agenda.item</code>.
     */
    public String getItem() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<Integer, Integer, Integer, LocalDateTime, LocalDateTime, String, String, LocalDateTime, String, String, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<Integer, Integer, Integer, LocalDateTime, LocalDateTime, String, String, LocalDateTime, String, String, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Agenda.AGENDA.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Agenda.AGENDA.MEMBER_ID;
    }

    @Override
    public Field<Integer> field3() {
        return Agenda.AGENDA.PROJECT_ID;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Agenda.AGENDA.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Agenda.AGENDA.UPDATE_TIME;
    }

    @Override
    public Field<String> field6() {
        return Agenda.AGENDA.NAME;
    }

    @Override
    public Field<String> field7() {
        return Agenda.AGENDA.DESCRIPTION;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return Agenda.AGENDA.FINISH_TIME;
    }

    @Override
    public Field<String> field9() {
        return Agenda.AGENDA.RESULT;
    }

    @Override
    public Field<String> field10() {
        return Agenda.AGENDA.STATUS;
    }

    @Override
    public Field<String> field11() {
        return Agenda.AGENDA.ITEM;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getMemberId();
    }

    @Override
    public Integer component3() {
        return getProjectId();
    }

    @Override
    public LocalDateTime component4() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component5() {
        return getUpdateTime();
    }

    @Override
    public String component6() {
        return getName();
    }

    @Override
    public String component7() {
        return getDescription();
    }

    @Override
    public LocalDateTime component8() {
        return getFinishTime();
    }

    @Override
    public String component9() {
        return getResult();
    }

    @Override
    public String component10() {
        return getStatus();
    }

    @Override
    public String component11() {
        return getItem();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getMemberId();
    }

    @Override
    public Integer value3() {
        return getProjectId();
    }

    @Override
    public LocalDateTime value4() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value5() {
        return getUpdateTime();
    }

    @Override
    public String value6() {
        return getName();
    }

    @Override
    public String value7() {
        return getDescription();
    }

    @Override
    public LocalDateTime value8() {
        return getFinishTime();
    }

    @Override
    public String value9() {
        return getResult();
    }

    @Override
    public String value10() {
        return getStatus();
    }

    @Override
    public String value11() {
        return getItem();
    }

    @Override
    public AgendaRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public AgendaRecord value2(Integer value) {
        setMemberId(value);
        return this;
    }

    @Override
    public AgendaRecord value3(Integer value) {
        setProjectId(value);
        return this;
    }

    @Override
    public AgendaRecord value4(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public AgendaRecord value5(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public AgendaRecord value6(String value) {
        setName(value);
        return this;
    }

    @Override
    public AgendaRecord value7(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public AgendaRecord value8(LocalDateTime value) {
        setFinishTime(value);
        return this;
    }

    @Override
    public AgendaRecord value9(String value) {
        setResult(value);
        return this;
    }

    @Override
    public AgendaRecord value10(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public AgendaRecord value11(String value) {
        setItem(value);
        return this;
    }

    @Override
    public AgendaRecord values(Integer value1, Integer value2, Integer value3, LocalDateTime value4, LocalDateTime value5, String value6, String value7, LocalDateTime value8, String value9, String value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AgendaRecord
     */
    public AgendaRecord() {
        super(Agenda.AGENDA);
    }

    /**
     * Create a detached, initialised AgendaRecord
     */
    public AgendaRecord(Integer id, Integer memberId, Integer projectId, LocalDateTime createTime, LocalDateTime updateTime, String name, String description, LocalDateTime finishTime, String result, String status, String item) {
        super(Agenda.AGENDA);

        set(0, id);
        set(1, memberId);
        set(2, projectId);
        set(3, createTime);
        set(4, updateTime);
        set(5, name);
        set(6, description);
        set(7, finishTime);
        set(8, result);
        set(9, status);
        set(10, item);
    }
}
