/*
 * This file is generated by jOOQ.
 */
package com.ymm.back.domain.tables.records;


import com.ymm.back.domain.tables.Comment;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CommentRecord extends UpdatableRecordImpl<CommentRecord> implements Record6<Integer, Integer, Integer, LocalDateTime, LocalDateTime, String> {

    private static final long serialVersionUID = -663101681;

    /**
     * Setter for <code>douzone.comment.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>douzone.comment.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>douzone.comment.member_id</code>.
     */
    public void setMemberId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>douzone.comment.member_id</code>.
     */
    public Integer getMemberId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>douzone.comment.work_id</code>.
     */
    public void setWorkId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>douzone.comment.work_id</code>.
     */
    public Integer getWorkId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>douzone.comment.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>douzone.comment.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>douzone.comment.update_time</code>.
     */
    public void setUpdateTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>douzone.comment.update_time</code>.
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>douzone.comment.comments</code>.
     */
    public void setComments(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>douzone.comment.comments</code>.
     */
    public String getComments() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Integer, Integer, LocalDateTime, LocalDateTime, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, Integer, Integer, LocalDateTime, LocalDateTime, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Comment.COMMENT.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Comment.COMMENT.MEMBER_ID;
    }

    @Override
    public Field<Integer> field3() {
        return Comment.COMMENT.WORK_ID;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Comment.COMMENT.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Comment.COMMENT.UPDATE_TIME;
    }

    @Override
    public Field<String> field6() {
        return Comment.COMMENT.COMMENTS;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getMemberId();
    }

    @Override
    public Integer component3() {
        return getWorkId();
    }

    @Override
    public LocalDateTime component4() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component5() {
        return getUpdateTime();
    }

    @Override
    public String component6() {
        return getComments();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getMemberId();
    }

    @Override
    public Integer value3() {
        return getWorkId();
    }

    @Override
    public LocalDateTime value4() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value5() {
        return getUpdateTime();
    }

    @Override
    public String value6() {
        return getComments();
    }

    @Override
    public CommentRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public CommentRecord value2(Integer value) {
        setMemberId(value);
        return this;
    }

    @Override
    public CommentRecord value3(Integer value) {
        setWorkId(value);
        return this;
    }

    @Override
    public CommentRecord value4(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public CommentRecord value5(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public CommentRecord value6(String value) {
        setComments(value);
        return this;
    }

    @Override
    public CommentRecord values(Integer value1, Integer value2, Integer value3, LocalDateTime value4, LocalDateTime value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CommentRecord
     */
    public CommentRecord() {
        super(Comment.COMMENT);
    }

    /**
     * Create a detached, initialised CommentRecord
     */
    public CommentRecord(Integer id, Integer memberId, Integer workId, LocalDateTime createTime, LocalDateTime updateTime, String comments) {
        super(Comment.COMMENT);

        set(0, id);
        set(1, memberId);
        set(2, workId);
        set(3, createTime);
        set(4, updateTime);
        set(5, comments);
    }
}
