/*
 * This file is generated by jOOQ.
 */
package com.ymm.back.domain.tables.records;


import com.ymm.back.domain.tables.FileStorage;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FileStorageRecord extends UpdatableRecordImpl<FileStorageRecord> implements Record6<Integer, Integer, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = -1744741012;

    /**
     * Setter for <code>douzone.file_storage.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>douzone.file_storage.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>douzone.file_storage.message_id</code>.
     */
    public void setMessageId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>douzone.file_storage.message_id</code>.
     */
    public Integer getMessageId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>douzone.file_storage.url</code>.
     */
    public void setUrl(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>douzone.file_storage.url</code>.
     */
    public String getUrl() {
        return (String) get(2);
    }

    /**
     * Setter for <code>douzone.file_storage.filename</code>.
     */
    public void setFilename(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>douzone.file_storage.filename</code>.
     */
    public String getFilename() {
        return (String) get(3);
    }

    /**
     * Setter for <code>douzone.file_storage.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>douzone.file_storage.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>douzone.file_storage.update_time</code>.
     */
    public void setUpdateTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>douzone.file_storage.update_time</code>.
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Integer, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, Integer, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return FileStorage.FILE_STORAGE.ID;
    }

    @Override
    public Field<Integer> field2() {
        return FileStorage.FILE_STORAGE.MESSAGE_ID;
    }

    @Override
    public Field<String> field3() {
        return FileStorage.FILE_STORAGE.URL;
    }

    @Override
    public Field<String> field4() {
        return FileStorage.FILE_STORAGE.FILENAME;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return FileStorage.FILE_STORAGE.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return FileStorage.FILE_STORAGE.UPDATE_TIME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getMessageId();
    }

    @Override
    public String component3() {
        return getUrl();
    }

    @Override
    public String component4() {
        return getFilename();
    }

    @Override
    public LocalDateTime component5() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component6() {
        return getUpdateTime();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getMessageId();
    }

    @Override
    public String value3() {
        return getUrl();
    }

    @Override
    public String value4() {
        return getFilename();
    }

    @Override
    public LocalDateTime value5() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value6() {
        return getUpdateTime();
    }

    @Override
    public FileStorageRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public FileStorageRecord value2(Integer value) {
        setMessageId(value);
        return this;
    }

    @Override
    public FileStorageRecord value3(String value) {
        setUrl(value);
        return this;
    }

    @Override
    public FileStorageRecord value4(String value) {
        setFilename(value);
        return this;
    }

    @Override
    public FileStorageRecord value5(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public FileStorageRecord value6(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public FileStorageRecord values(Integer value1, Integer value2, String value3, String value4, LocalDateTime value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FileStorageRecord
     */
    public FileStorageRecord() {
        super(FileStorage.FILE_STORAGE);
    }

    /**
     * Create a detached, initialised FileStorageRecord
     */
    public FileStorageRecord(Integer id, Integer messageId, String url, String filename, LocalDateTime createTime, LocalDateTime updateTime) {
        super(FileStorage.FILE_STORAGE);

        set(0, id);
        set(1, messageId);
        set(2, url);
        set(3, filename);
        set(4, createTime);
        set(5, updateTime);
    }
}
