/*
 * This file is generated by jOOQ.
 */
package com.ymm.back.domain.tables.records;


import com.ymm.back.domain.tables.FileStorage;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FileStorageRecord extends UpdatableRecordImpl<FileStorageRecord> implements Record5<Integer, String, String, Integer, String> {

    private static final long serialVersionUID = -186463724;

    /**
     * Setter for <code>hwant.file_storage.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>hwant.file_storage.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>hwant.file_storage.url</code>.
     */
    public void setUrl(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>hwant.file_storage.url</code>.
     */
    public String getUrl() {
        return (String) get(1);
    }

    /**
     * Setter for <code>hwant.file_storage.file_name</code>.
     */
    public void setFileName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>hwant.file_storage.file_name</code>.
     */
    public String getFileName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>hwant.file_storage.message_fk</code>.
     */
    public void setMessageFk(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>hwant.file_storage.message_fk</code>.
     */
    public Integer getMessageFk() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>hwant.file_storage.created_at</code>.
     */
    public void setCreatedAt(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>hwant.file_storage.created_at</code>.
     */
    public String getCreatedAt() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, Integer, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, String, Integer, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return FileStorage.FILE_STORAGE.ID;
    }

    @Override
    public Field<String> field2() {
        return FileStorage.FILE_STORAGE.URL;
    }

    @Override
    public Field<String> field3() {
        return FileStorage.FILE_STORAGE.FILE_NAME;
    }

    @Override
    public Field<Integer> field4() {
        return FileStorage.FILE_STORAGE.MESSAGE_FK;
    }

    @Override
    public Field<String> field5() {
        return FileStorage.FILE_STORAGE.CREATED_AT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUrl();
    }

    @Override
    public String component3() {
        return getFileName();
    }

    @Override
    public Integer component4() {
        return getMessageFk();
    }

    @Override
    public String component5() {
        return getCreatedAt();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUrl();
    }

    @Override
    public String value3() {
        return getFileName();
    }

    @Override
    public Integer value4() {
        return getMessageFk();
    }

    @Override
    public String value5() {
        return getCreatedAt();
    }

    @Override
    public FileStorageRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public FileStorageRecord value2(String value) {
        setUrl(value);
        return this;
    }

    @Override
    public FileStorageRecord value3(String value) {
        setFileName(value);
        return this;
    }

    @Override
    public FileStorageRecord value4(Integer value) {
        setMessageFk(value);
        return this;
    }

    @Override
    public FileStorageRecord value5(String value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public FileStorageRecord values(Integer value1, String value2, String value3, Integer value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FileStorageRecord
     */
    public FileStorageRecord() {
        super(FileStorage.FILE_STORAGE);
    }

    /**
     * Create a detached, initialised FileStorageRecord
     */
    public FileStorageRecord(Integer id, String url, String fileName, Integer messageFk, String createdAt) {
        super(FileStorage.FILE_STORAGE);

        set(0, id);
        set(1, url);
        set(2, fileName);
        set(3, messageFk);
        set(4, createdAt);
    }
}
