/*
 * This file is generated by jOOQ.
 */
package com.ymm.back.domain.tables.records;


import com.ymm.back.domain.tables.Hashtag;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HashtagRecord extends UpdatableRecordImpl<HashtagRecord> implements Record5<Integer, Integer, LocalDateTime, LocalDateTime, String> {

    private static final long serialVersionUID = 1037001145;

    /**
     * Setter for <code>douzone.hashtag.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>douzone.hashtag.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>douzone.hashtag.work_id</code>.
     */
    public void setWorkId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>douzone.hashtag.work_id</code>.
     */
    public Integer getWorkId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>douzone.hashtag.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>douzone.hashtag.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>douzone.hashtag.update_time</code>.
     */
    public void setUpdateTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>douzone.hashtag.update_time</code>.
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>douzone.hashtag.name</code>.
     */
    public void setName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>douzone.hashtag.name</code>.
     */
    public String getName() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, LocalDateTime, LocalDateTime, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, LocalDateTime, LocalDateTime, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Hashtag.HASHTAG.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Hashtag.HASHTAG.WORK_ID;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return Hashtag.HASHTAG.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Hashtag.HASHTAG.UPDATE_TIME;
    }

    @Override
    public Field<String> field5() {
        return Hashtag.HASHTAG.NAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getWorkId();
    }

    @Override
    public LocalDateTime component3() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component4() {
        return getUpdateTime();
    }

    @Override
    public String component5() {
        return getName();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getWorkId();
    }

    @Override
    public LocalDateTime value3() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value4() {
        return getUpdateTime();
    }

    @Override
    public String value5() {
        return getName();
    }

    @Override
    public HashtagRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public HashtagRecord value2(Integer value) {
        setWorkId(value);
        return this;
    }

    @Override
    public HashtagRecord value3(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public HashtagRecord value4(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public HashtagRecord value5(String value) {
        setName(value);
        return this;
    }

    @Override
    public HashtagRecord values(Integer value1, Integer value2, LocalDateTime value3, LocalDateTime value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HashtagRecord
     */
    public HashtagRecord() {
        super(Hashtag.HASHTAG);
    }

    /**
     * Create a detached, initialised HashtagRecord
     */
    public HashtagRecord(Integer id, Integer workId, LocalDateTime createTime, LocalDateTime updateTime, String name) {
        super(Hashtag.HASHTAG);

        set(0, id);
        set(1, workId);
        set(2, createTime);
        set(3, updateTime);
        set(4, name);
    }
}
