/*
 * This file is generated by jOOQ.
 */
package com.ymm.back.domain.tables.records;


import com.ymm.back.domain.tables.Member;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MemberRecord extends UpdatableRecordImpl<MemberRecord> implements Record7<Integer, Integer, Integer, LocalDateTime, LocalDateTime, String, String> {

    private static final long serialVersionUID = -649129098;

    /**
     * Setter for <code>douzone.member.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>douzone.member.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>douzone.member.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>douzone.member.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>douzone.member.project_id</code>.
     */
    public void setProjectId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>douzone.member.project_id</code>.
     */
    public Integer getProjectId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>douzone.member.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>douzone.member.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>douzone.member.update_time</code>.
     */
    public void setUpdateTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>douzone.member.update_time</code>.
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>douzone.member.name</code>.
     */
    public void setName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>douzone.member.name</code>.
     */
    public String getName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>douzone.member.status</code>.
     */
    public void setStatus(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>douzone.member.status</code>.
     */
    public String getStatus() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, Integer, Integer, LocalDateTime, LocalDateTime, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, Integer, Integer, LocalDateTime, LocalDateTime, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Member.MEMBER.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Member.MEMBER.USER_ID;
    }

    @Override
    public Field<Integer> field3() {
        return Member.MEMBER.PROJECT_ID;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Member.MEMBER.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Member.MEMBER.UPDATE_TIME;
    }

    @Override
    public Field<String> field6() {
        return Member.MEMBER.NAME;
    }

    @Override
    public Field<String> field7() {
        return Member.MEMBER.STATUS;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getUserId();
    }

    @Override
    public Integer component3() {
        return getProjectId();
    }

    @Override
    public LocalDateTime component4() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component5() {
        return getUpdateTime();
    }

    @Override
    public String component6() {
        return getName();
    }

    @Override
    public String component7() {
        return getStatus();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getUserId();
    }

    @Override
    public Integer value3() {
        return getProjectId();
    }

    @Override
    public LocalDateTime value4() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value5() {
        return getUpdateTime();
    }

    @Override
    public String value6() {
        return getName();
    }

    @Override
    public String value7() {
        return getStatus();
    }

    @Override
    public MemberRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public MemberRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public MemberRecord value3(Integer value) {
        setProjectId(value);
        return this;
    }

    @Override
    public MemberRecord value4(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public MemberRecord value5(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public MemberRecord value6(String value) {
        setName(value);
        return this;
    }

    @Override
    public MemberRecord value7(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public MemberRecord values(Integer value1, Integer value2, Integer value3, LocalDateTime value4, LocalDateTime value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MemberRecord
     */
    public MemberRecord() {
        super(Member.MEMBER);
    }

    /**
     * Create a detached, initialised MemberRecord
     */
    public MemberRecord(Integer id, Integer userId, Integer projectId, LocalDateTime createTime, LocalDateTime updateTime, String name, String status) {
        super(Member.MEMBER);

        set(0, id);
        set(1, userId);
        set(2, projectId);
        set(3, createTime);
        set(4, updateTime);
        set(5, name);
        set(6, status);
    }
}
