/*
 * This file is generated by jOOQ.
 */
package com.ymm.back.domain.tables.records;


import com.ymm.back.domain.tables.Message;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MessageRecord extends UpdatableRecordImpl<MessageRecord> implements Record7<Integer, Integer, Integer, LocalDateTime, LocalDateTime, String, String> {

    private static final long serialVersionUID = 239807582;

    /**
     * Setter for <code>douzone.message.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>douzone.message.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>douzone.message.member_id</code>.
     */
    public void setMemberId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>douzone.message.member_id</code>.
     */
    public Integer getMemberId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>douzone.message.project_id</code>.
     */
    public void setProjectId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>douzone.message.project_id</code>.
     */
    public Integer getProjectId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>douzone.message.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>douzone.message.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>douzone.message.update_time</code>.
     */
    public void setUpdateTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>douzone.message.update_time</code>.
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>douzone.message.message</code>.
     */
    public void setMessage(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>douzone.message.message</code>.
     */
    public String getMessage() {
        return (String) get(5);
    }

    /**
     * Setter for <code>douzone.message.type</code>.
     */
    public void setType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>douzone.message.type</code>.
     */
    public String getType() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, Integer, Integer, LocalDateTime, LocalDateTime, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, Integer, Integer, LocalDateTime, LocalDateTime, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Message.MESSAGE.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Message.MESSAGE.MEMBER_ID;
    }

    @Override
    public Field<Integer> field3() {
        return Message.MESSAGE.PROJECT_ID;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Message.MESSAGE.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Message.MESSAGE.UPDATE_TIME;
    }

    @Override
    public Field<String> field6() {
        return Message.MESSAGE.MESSAGE_;
    }

    @Override
    public Field<String> field7() {
        return Message.MESSAGE.TYPE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getMemberId();
    }

    @Override
    public Integer component3() {
        return getProjectId();
    }

    @Override
    public LocalDateTime component4() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component5() {
        return getUpdateTime();
    }

    @Override
    public String component6() {
        return getMessage();
    }

    @Override
    public String component7() {
        return getType();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getMemberId();
    }

    @Override
    public Integer value3() {
        return getProjectId();
    }

    @Override
    public LocalDateTime value4() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value5() {
        return getUpdateTime();
    }

    @Override
    public String value6() {
        return getMessage();
    }

    @Override
    public String value7() {
        return getType();
    }

    @Override
    public MessageRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public MessageRecord value2(Integer value) {
        setMemberId(value);
        return this;
    }

    @Override
    public MessageRecord value3(Integer value) {
        setProjectId(value);
        return this;
    }

    @Override
    public MessageRecord value4(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public MessageRecord value5(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public MessageRecord value6(String value) {
        setMessage(value);
        return this;
    }

    @Override
    public MessageRecord value7(String value) {
        setType(value);
        return this;
    }

    @Override
    public MessageRecord values(Integer value1, Integer value2, Integer value3, LocalDateTime value4, LocalDateTime value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MessageRecord
     */
    public MessageRecord() {
        super(Message.MESSAGE);
    }

    /**
     * Create a detached, initialised MessageRecord
     */
    public MessageRecord(Integer id, Integer memberId, Integer projectId, LocalDateTime createTime, LocalDateTime updateTime, String message, String type) {
        super(Message.MESSAGE);

        set(0, id);
        set(1, memberId);
        set(2, projectId);
        set(3, createTime);
        set(4, updateTime);
        set(5, message);
        set(6, type);
    }
}
