/*
 * This file is generated by jOOQ.
 */
package com.ymm.back.domain.tables.records;


import com.ymm.back.domain.tables.Message;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MessageRecord extends UpdatableRecordImpl<MessageRecord> implements Record6<Integer, String, Integer, Integer, String, String> {

    private static final long serialVersionUID = 2102005175;

    /**
     * Setter for <code>hwant.message.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>hwant.message.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>hwant.message.message</code>.
     */
    public void setMessage(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>hwant.message.message</code>.
     */
    public String getMessage() {
        return (String) get(1);
    }

    /**
     * Setter for <code>hwant.message.project_member_fk</code>.
     */
    public void setProjectMemberFk(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>hwant.message.project_member_fk</code>.
     */
    public Integer getProjectMemberFk() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>hwant.message.project_fk</code>.
     */
    public void setProjectFk(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>hwant.message.project_fk</code>.
     */
    public Integer getProjectFk() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>hwant.message.type</code>.
     */
    public void setType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>hwant.message.type</code>.
     */
    public String getType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>hwant.message.created_at</code>.
     */
    public void setCreatedAt(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>hwant.message.created_at</code>.
     */
    public String getCreatedAt() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, Integer, Integer, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, Integer, Integer, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Message.MESSAGE.ID;
    }

    @Override
    public Field<String> field2() {
        return Message.MESSAGE.MESSAGE_;
    }

    @Override
    public Field<Integer> field3() {
        return Message.MESSAGE.PROJECT_MEMBER_FK;
    }

    @Override
    public Field<Integer> field4() {
        return Message.MESSAGE.PROJECT_FK;
    }

    @Override
    public Field<String> field5() {
        return Message.MESSAGE.TYPE;
    }

    @Override
    public Field<String> field6() {
        return Message.MESSAGE.CREATED_AT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getMessage();
    }

    @Override
    public Integer component3() {
        return getProjectMemberFk();
    }

    @Override
    public Integer component4() {
        return getProjectFk();
    }

    @Override
    public String component5() {
        return getType();
    }

    @Override
    public String component6() {
        return getCreatedAt();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getMessage();
    }

    @Override
    public Integer value3() {
        return getProjectMemberFk();
    }

    @Override
    public Integer value4() {
        return getProjectFk();
    }

    @Override
    public String value5() {
        return getType();
    }

    @Override
    public String value6() {
        return getCreatedAt();
    }

    @Override
    public MessageRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public MessageRecord value2(String value) {
        setMessage(value);
        return this;
    }

    @Override
    public MessageRecord value3(Integer value) {
        setProjectMemberFk(value);
        return this;
    }

    @Override
    public MessageRecord value4(Integer value) {
        setProjectFk(value);
        return this;
    }

    @Override
    public MessageRecord value5(String value) {
        setType(value);
        return this;
    }

    @Override
    public MessageRecord value6(String value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public MessageRecord values(Integer value1, String value2, Integer value3, Integer value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MessageRecord
     */
    public MessageRecord() {
        super(Message.MESSAGE);
    }

    /**
     * Create a detached, initialised MessageRecord
     */
    public MessageRecord(Integer id, String message, Integer projectMemberFk, Integer projectFk, String type, String createdAt) {
        super(Message.MESSAGE);

        set(0, id);
        set(1, message);
        set(2, projectMemberFk);
        set(3, projectFk);
        set(4, type);
        set(5, createdAt);
    }
}
