/*
 * This file is generated by jOOQ.
 */
package com.ymm.back.domain.tables.records;


import com.ymm.back.domain.tables.ProjectMember;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProjectMemberRecord extends UpdatableRecordImpl<ProjectMemberRecord> implements Record13<Integer, Integer, Integer, String, String, String, String, String, String, String, LocalDateTime, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 417424111;

    /**
     * Setter for <code>project_member.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>project_member.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>project_member.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>project_member.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>project_member.project_id</code>.
     */
    public void setProjectId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>project_member.project_id</code>.
     */
    public Integer getProjectId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>project_member.status</code>.
     */
    public void setStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>project_member.status</code>.
     */
    public String getStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>project_member.applied_position</code>.
     */
    public void setAppliedPosition(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>project_member.applied_position</code>.
     */
    public String getAppliedPosition() {
        return (String) get(4);
    }

    /**
     * Setter for <code>project_member.comments</code>.
     */
    public void setComments(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>project_member.comments</code>.
     */
    public String getComments() {
        return (String) get(5);
    }

    /**
     * Setter for <code>project_member.portfolio_file</code>.
     */
    public void setPortfolioFile(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>project_member.portfolio_file</code>.
     */
    public String getPortfolioFile() {
        return (String) get(6);
    }

    /**
     * Setter for <code>project_member.portfolio_url</code>.
     */
    public void setPortfolioUrl(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>project_member.portfolio_url</code>.
     */
    public String getPortfolioUrl() {
        return (String) get(7);
    }

    /**
     * Setter for <code>project_member.description</code>.
     */
    public void setDescription(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>project_member.description</code>.
     */
    public String getDescription() {
        return (String) get(8);
    }

    /**
     * Setter for <code>project_member.auth</code>.
     */
    public void setAuth(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>project_member.auth</code>.
     */
    public String getAuth() {
        return (String) get(9);
    }

    /**
     * Setter for <code>project_member.applied_time</code>.
     */
    public void setAppliedTime(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>project_member.applied_time</code>.
     */
    public LocalDateTime getAppliedTime() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>project_member.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>project_member.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>project_member.update_time</code>.
     */
    public void setUpdateTime(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>project_member.update_time</code>.
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<Integer, Integer, Integer, String, String, String, String, String, String, String, LocalDateTime, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<Integer, Integer, Integer, String, String, String, String, String, String, String, LocalDateTime, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ProjectMember.PROJECT_MEMBER.ID;
    }

    @Override
    public Field<Integer> field2() {
        return ProjectMember.PROJECT_MEMBER.USER_ID;
    }

    @Override
    public Field<Integer> field3() {
        return ProjectMember.PROJECT_MEMBER.PROJECT_ID;
    }

    @Override
    public Field<String> field4() {
        return ProjectMember.PROJECT_MEMBER.STATUS;
    }

    @Override
    public Field<String> field5() {
        return ProjectMember.PROJECT_MEMBER.APPLIED_POSITION;
    }

    @Override
    public Field<String> field6() {
        return ProjectMember.PROJECT_MEMBER.COMMENTS;
    }

    @Override
    public Field<String> field7() {
        return ProjectMember.PROJECT_MEMBER.PORTFOLIO_FILE;
    }

    @Override
    public Field<String> field8() {
        return ProjectMember.PROJECT_MEMBER.PORTFOLIO_URL;
    }

    @Override
    public Field<String> field9() {
        return ProjectMember.PROJECT_MEMBER.DESCRIPTION;
    }

    @Override
    public Field<String> field10() {
        return ProjectMember.PROJECT_MEMBER.AUTH;
    }

    @Override
    public Field<LocalDateTime> field11() {
        return ProjectMember.PROJECT_MEMBER.APPLIED_TIME;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return ProjectMember.PROJECT_MEMBER.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field13() {
        return ProjectMember.PROJECT_MEMBER.UPDATE_TIME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getUserId();
    }

    @Override
    public Integer component3() {
        return getProjectId();
    }

    @Override
    public String component4() {
        return getStatus();
    }

    @Override
    public String component5() {
        return getAppliedPosition();
    }

    @Override
    public String component6() {
        return getComments();
    }

    @Override
    public String component7() {
        return getPortfolioFile();
    }

    @Override
    public String component8() {
        return getPortfolioUrl();
    }

    @Override
    public String component9() {
        return getDescription();
    }

    @Override
    public String component10() {
        return getAuth();
    }

    @Override
    public LocalDateTime component11() {
        return getAppliedTime();
    }

    @Override
    public LocalDateTime component12() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component13() {
        return getUpdateTime();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getUserId();
    }

    @Override
    public Integer value3() {
        return getProjectId();
    }

    @Override
    public String value4() {
        return getStatus();
    }

    @Override
    public String value5() {
        return getAppliedPosition();
    }

    @Override
    public String value6() {
        return getComments();
    }

    @Override
    public String value7() {
        return getPortfolioFile();
    }

    @Override
    public String value8() {
        return getPortfolioUrl();
    }

    @Override
    public String value9() {
        return getDescription();
    }

    @Override
    public String value10() {
        return getAuth();
    }

    @Override
    public LocalDateTime value11() {
        return getAppliedTime();
    }

    @Override
    public LocalDateTime value12() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value13() {
        return getUpdateTime();
    }

    @Override
    public ProjectMemberRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ProjectMemberRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public ProjectMemberRecord value3(Integer value) {
        setProjectId(value);
        return this;
    }

    @Override
    public ProjectMemberRecord value4(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public ProjectMemberRecord value5(String value) {
        setAppliedPosition(value);
        return this;
    }

    @Override
    public ProjectMemberRecord value6(String value) {
        setComments(value);
        return this;
    }

    @Override
    public ProjectMemberRecord value7(String value) {
        setPortfolioFile(value);
        return this;
    }

    @Override
    public ProjectMemberRecord value8(String value) {
        setPortfolioUrl(value);
        return this;
    }

    @Override
    public ProjectMemberRecord value9(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public ProjectMemberRecord value10(String value) {
        setAuth(value);
        return this;
    }

    @Override
    public ProjectMemberRecord value11(LocalDateTime value) {
        setAppliedTime(value);
        return this;
    }

    @Override
    public ProjectMemberRecord value12(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public ProjectMemberRecord value13(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public ProjectMemberRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, LocalDateTime value11, LocalDateTime value12, LocalDateTime value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjectMemberRecord
     */
    public ProjectMemberRecord() {
        super(ProjectMember.PROJECT_MEMBER);
    }

    /**
     * Create a detached, initialised ProjectMemberRecord
     */
    public ProjectMemberRecord(Integer id, Integer userId, Integer projectId, String status, String appliedPosition, String comments, String portfolioFile, String portfolioUrl, String description, String auth, LocalDateTime appliedTime, LocalDateTime createTime, LocalDateTime updateTime) {
        super(ProjectMember.PROJECT_MEMBER);

        set(0, id);
        set(1, userId);
        set(2, projectId);
        set(3, status);
        set(4, appliedPosition);
        set(5, comments);
        set(6, portfolioFile);
        set(7, portfolioUrl);
        set(8, description);
        set(9, auth);
        set(10, appliedTime);
        set(11, createTime);
        set(12, updateTime);
    }
}
