/*
 * This file is generated by jOOQ.
 */
package com.ymm.back.domain.tables.records;


import com.ymm.back.domain.tables.ProjectMember;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProjectMemberRecord extends UpdatableRecordImpl<ProjectMemberRecord> implements Record13<Integer, String, String, String, String, String, String, String, String, Integer, String, Integer, Integer> {

    private static final long serialVersionUID = -1375984931;

    /**
     * Setter for <code>hwant.project_member.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>hwant.project_member.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>hwant.project_member.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>hwant.project_member.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>hwant.project_member.user_name</code>.
     */
    public void setUserName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>hwant.project_member.user_name</code>.
     */
    public String getUserName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>hwant.project_member.applied_position</code>.
     */
    public void setAppliedPosition(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>hwant.project_member.applied_position</code>.
     */
    public String getAppliedPosition() {
        return (String) get(3);
    }

    /**
     * Setter for <code>hwant.project_member.comments</code>.
     */
    public void setComments(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>hwant.project_member.comments</code>.
     */
    public String getComments() {
        return (String) get(4);
    }

    /**
     * Setter for <code>hwant.project_member.portfolio_file</code>.
     */
    public void setPortfolioFile(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>hwant.project_member.portfolio_file</code>.
     */
    public String getPortfolioFile() {
        return (String) get(5);
    }

    /**
     * Setter for <code>hwant.project_member.portfolio_url</code>.
     */
    public void setPortfolioUrl(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>hwant.project_member.portfolio_url</code>.
     */
    public String getPortfolioUrl() {
        return (String) get(6);
    }

    /**
     * Setter for <code>hwant.project_member.description</code>.
     */
    public void setDescription(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>hwant.project_member.description</code>.
     */
    public String getDescription() {
        return (String) get(7);
    }

    /**
     * Setter for <code>hwant.project_member.auth</code>.
     */
    public void setAuth(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>hwant.project_member.auth</code>.
     */
    public String getAuth() {
        return (String) get(8);
    }

    /**
     * Setter for <code>hwant.project_member.role_id</code>.
     */
    public void setRoleId(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>hwant.project_member.role_id</code>.
     */
    public Integer getRoleId() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>hwant.project_member.websocket</code>.
     */
    public void setWebsocket(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>hwant.project_member.websocket</code>.
     */
    public String getWebsocket() {
        return (String) get(10);
    }

    /**
     * Setter for <code>hwant.project_member.user_fk</code>.
     */
    public void setUserFk(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>hwant.project_member.user_fk</code>.
     */
    public Integer getUserFk() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>hwant.project_member.project_fk</code>.
     */
    public void setProjectFk(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>hwant.project_member.project_fk</code>.
     */
    public Integer getProjectFk() {
        return (Integer) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<Integer, String, String, String, String, String, String, String, String, Integer, String, Integer, Integer> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<Integer, String, String, String, String, String, String, String, String, Integer, String, Integer, Integer> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ProjectMember.PROJECT_MEMBER.ID;
    }

    @Override
    public Field<String> field2() {
        return ProjectMember.PROJECT_MEMBER.NAME;
    }

    @Override
    public Field<String> field3() {
        return ProjectMember.PROJECT_MEMBER.USER_NAME;
    }

    @Override
    public Field<String> field4() {
        return ProjectMember.PROJECT_MEMBER.APPLIED_POSITION;
    }

    @Override
    public Field<String> field5() {
        return ProjectMember.PROJECT_MEMBER.COMMENTS;
    }

    @Override
    public Field<String> field6() {
        return ProjectMember.PROJECT_MEMBER.PORTFOLIO_FILE;
    }

    @Override
    public Field<String> field7() {
        return ProjectMember.PROJECT_MEMBER.PORTFOLIO_URL;
    }

    @Override
    public Field<String> field8() {
        return ProjectMember.PROJECT_MEMBER.DESCRIPTION;
    }

    @Override
    public Field<String> field9() {
        return ProjectMember.PROJECT_MEMBER.AUTH;
    }

    @Override
    public Field<Integer> field10() {
        return ProjectMember.PROJECT_MEMBER.ROLE_ID;
    }

    @Override
    public Field<String> field11() {
        return ProjectMember.PROJECT_MEMBER.WEBSOCKET;
    }

    @Override
    public Field<Integer> field12() {
        return ProjectMember.PROJECT_MEMBER.USER_FK;
    }

    @Override
    public Field<Integer> field13() {
        return ProjectMember.PROJECT_MEMBER.PROJECT_FK;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getUserName();
    }

    @Override
    public String component4() {
        return getAppliedPosition();
    }

    @Override
    public String component5() {
        return getComments();
    }

    @Override
    public String component6() {
        return getPortfolioFile();
    }

    @Override
    public String component7() {
        return getPortfolioUrl();
    }

    @Override
    public String component8() {
        return getDescription();
    }

    @Override
    public String component9() {
        return getAuth();
    }

    @Override
    public Integer component10() {
        return getRoleId();
    }

    @Override
    public String component11() {
        return getWebsocket();
    }

    @Override
    public Integer component12() {
        return getUserFk();
    }

    @Override
    public Integer component13() {
        return getProjectFk();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getUserName();
    }

    @Override
    public String value4() {
        return getAppliedPosition();
    }

    @Override
    public String value5() {
        return getComments();
    }

    @Override
    public String value6() {
        return getPortfolioFile();
    }

    @Override
    public String value7() {
        return getPortfolioUrl();
    }

    @Override
    public String value8() {
        return getDescription();
    }

    @Override
    public String value9() {
        return getAuth();
    }

    @Override
    public Integer value10() {
        return getRoleId();
    }

    @Override
    public String value11() {
        return getWebsocket();
    }

    @Override
    public Integer value12() {
        return getUserFk();
    }

    @Override
    public Integer value13() {
        return getProjectFk();
    }

    @Override
    public ProjectMemberRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ProjectMemberRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ProjectMemberRecord value3(String value) {
        setUserName(value);
        return this;
    }

    @Override
    public ProjectMemberRecord value4(String value) {
        setAppliedPosition(value);
        return this;
    }

    @Override
    public ProjectMemberRecord value5(String value) {
        setComments(value);
        return this;
    }

    @Override
    public ProjectMemberRecord value6(String value) {
        setPortfolioFile(value);
        return this;
    }

    @Override
    public ProjectMemberRecord value7(String value) {
        setPortfolioUrl(value);
        return this;
    }

    @Override
    public ProjectMemberRecord value8(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public ProjectMemberRecord value9(String value) {
        setAuth(value);
        return this;
    }

    @Override
    public ProjectMemberRecord value10(Integer value) {
        setRoleId(value);
        return this;
    }

    @Override
    public ProjectMemberRecord value11(String value) {
        setWebsocket(value);
        return this;
    }

    @Override
    public ProjectMemberRecord value12(Integer value) {
        setUserFk(value);
        return this;
    }

    @Override
    public ProjectMemberRecord value13(Integer value) {
        setProjectFk(value);
        return this;
    }

    @Override
    public ProjectMemberRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, Integer value10, String value11, Integer value12, Integer value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjectMemberRecord
     */
    public ProjectMemberRecord() {
        super(ProjectMember.PROJECT_MEMBER);
    }

    /**
     * Create a detached, initialised ProjectMemberRecord
     */
    public ProjectMemberRecord(Integer id, String name, String userName, String appliedPosition, String comments, String portfolioFile, String portfolioUrl, String description, String auth, Integer roleId, String websocket, Integer userFk, Integer projectFk) {
        super(ProjectMember.PROJECT_MEMBER);

        set(0, id);
        set(1, name);
        set(2, userName);
        set(3, appliedPosition);
        set(4, comments);
        set(5, portfolioFile);
        set(6, portfolioUrl);
        set(7, description);
        set(8, auth);
        set(9, roleId);
        set(10, websocket);
        set(11, userFk);
        set(12, projectFk);
    }
}
