/*
 * This file is generated by jOOQ.
 */
package com.ymm.back.domain.tables.records;


import com.ymm.back.domain.tables.Project;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProjectRecord extends UpdatableRecordImpl<ProjectRecord> implements Record16<Integer, Integer, String, String, Integer, String, String, String, Integer, String, String, Integer, LocalDateTime, LocalDateTime, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = -1553070202;

    /**
     * Setter for <code>project.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>project.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>project.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>project.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>project.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>project.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>project.contents</code>.
     */
    public void setContents(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>project.contents</code>.
     */
    public String getContents() {
        return (String) get(3);
    }

    /**
     * Setter for <code>project.view_count</code>.
     */
    public void setViewCount(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>project.view_count</code>.
     */
    public Integer getViewCount() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>project.thumbnail</code>.
     */
    public void setThumbnail(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>project.thumbnail</code>.
     */
    public String getThumbnail() {
        return (String) get(5);
    }

    /**
     * Setter for <code>project.description</code>.
     */
    public void setDescription(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>project.description</code>.
     */
    public String getDescription() {
        return (String) get(6);
    }

    /**
     * Setter for <code>project.authority</code>.
     */
    public void setAuthority(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>project.authority</code>.
     */
    public String getAuthority() {
        return (String) get(7);
    }

    /**
     * Setter for <code>project.total</code>.
     */
    public void setTotal(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>project.total</code>.
     */
    public Integer getTotal() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>project.type</code>.
     */
    public void setType(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>project.type</code>.
     */
    public String getType() {
        return (String) get(9);
    }

    /**
     * Setter for <code>project.url</code>.
     */
    public void setUrl(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>project.url</code>.
     */
    public String getUrl() {
        return (String) get(10);
    }

    /**
     * Setter for <code>project.to</code>.
     */
    public void setTo(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>project.to</code>.
     */
    public Integer getTo() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>project.started_time</code>.
     */
    public void setStartedTime(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>project.started_time</code>.
     */
    public LocalDateTime getStartedTime() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>project.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>project.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>project.update_time</code>.
     */
    public void setUpdateTime(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>project.update_time</code>.
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>project.finished_time</code>.
     */
    public void setFinishedTime(LocalDateTime value) {
        set(15, value);
    }

    /**
     * Getter for <code>project.finished_time</code>.
     */
    public LocalDateTime getFinishedTime() {
        return (LocalDateTime) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row16<Integer, Integer, String, String, Integer, String, String, String, Integer, String, String, Integer, LocalDateTime, LocalDateTime, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    @Override
    public Row16<Integer, Integer, String, String, Integer, String, String, String, Integer, String, String, Integer, LocalDateTime, LocalDateTime, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row16) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Project.PROJECT.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Project.PROJECT.USER_ID;
    }

    @Override
    public Field<String> field3() {
        return Project.PROJECT.NAME;
    }

    @Override
    public Field<String> field4() {
        return Project.PROJECT.CONTENTS;
    }

    @Override
    public Field<Integer> field5() {
        return Project.PROJECT.VIEW_COUNT;
    }

    @Override
    public Field<String> field6() {
        return Project.PROJECT.THUMBNAIL;
    }

    @Override
    public Field<String> field7() {
        return Project.PROJECT.DESCRIPTION;
    }

    @Override
    public Field<String> field8() {
        return Project.PROJECT.AUTHORITY;
    }

    @Override
    public Field<Integer> field9() {
        return Project.PROJECT.TOTAL;
    }

    @Override
    public Field<String> field10() {
        return Project.PROJECT.TYPE;
    }

    @Override
    public Field<String> field11() {
        return Project.PROJECT.URL;
    }

    @Override
    public Field<Integer> field12() {
        return Project.PROJECT.TO;
    }

    @Override
    public Field<LocalDateTime> field13() {
        return Project.PROJECT.STARTED_TIME;
    }

    @Override
    public Field<LocalDateTime> field14() {
        return Project.PROJECT.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field15() {
        return Project.PROJECT.UPDATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field16() {
        return Project.PROJECT.FINISHED_TIME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getUserId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getContents();
    }

    @Override
    public Integer component5() {
        return getViewCount();
    }

    @Override
    public String component6() {
        return getThumbnail();
    }

    @Override
    public String component7() {
        return getDescription();
    }

    @Override
    public String component8() {
        return getAuthority();
    }

    @Override
    public Integer component9() {
        return getTotal();
    }

    @Override
    public String component10() {
        return getType();
    }

    @Override
    public String component11() {
        return getUrl();
    }

    @Override
    public Integer component12() {
        return getTo();
    }

    @Override
    public LocalDateTime component13() {
        return getStartedTime();
    }

    @Override
    public LocalDateTime component14() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component15() {
        return getUpdateTime();
    }

    @Override
    public LocalDateTime component16() {
        return getFinishedTime();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getUserId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getContents();
    }

    @Override
    public Integer value5() {
        return getViewCount();
    }

    @Override
    public String value6() {
        return getThumbnail();
    }

    @Override
    public String value7() {
        return getDescription();
    }

    @Override
    public String value8() {
        return getAuthority();
    }

    @Override
    public Integer value9() {
        return getTotal();
    }

    @Override
    public String value10() {
        return getType();
    }

    @Override
    public String value11() {
        return getUrl();
    }

    @Override
    public Integer value12() {
        return getTo();
    }

    @Override
    public LocalDateTime value13() {
        return getStartedTime();
    }

    @Override
    public LocalDateTime value14() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value15() {
        return getUpdateTime();
    }

    @Override
    public LocalDateTime value16() {
        return getFinishedTime();
    }

    @Override
    public ProjectRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ProjectRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public ProjectRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public ProjectRecord value4(String value) {
        setContents(value);
        return this;
    }

    @Override
    public ProjectRecord value5(Integer value) {
        setViewCount(value);
        return this;
    }

    @Override
    public ProjectRecord value6(String value) {
        setThumbnail(value);
        return this;
    }

    @Override
    public ProjectRecord value7(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public ProjectRecord value8(String value) {
        setAuthority(value);
        return this;
    }

    @Override
    public ProjectRecord value9(Integer value) {
        setTotal(value);
        return this;
    }

    @Override
    public ProjectRecord value10(String value) {
        setType(value);
        return this;
    }

    @Override
    public ProjectRecord value11(String value) {
        setUrl(value);
        return this;
    }

    @Override
    public ProjectRecord value12(Integer value) {
        setTo(value);
        return this;
    }

    @Override
    public ProjectRecord value13(LocalDateTime value) {
        setStartedTime(value);
        return this;
    }

    @Override
    public ProjectRecord value14(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public ProjectRecord value15(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public ProjectRecord value16(LocalDateTime value) {
        setFinishedTime(value);
        return this;
    }

    @Override
    public ProjectRecord values(Integer value1, Integer value2, String value3, String value4, Integer value5, String value6, String value7, String value8, Integer value9, String value10, String value11, Integer value12, LocalDateTime value13, LocalDateTime value14, LocalDateTime value15, LocalDateTime value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjectRecord
     */
    public ProjectRecord() {
        super(Project.PROJECT);
    }

    /**
     * Create a detached, initialised ProjectRecord
     */
    public ProjectRecord(Integer id, Integer userId, String name, String contents, Integer viewCount, String thumbnail, String description, String authority, Integer total, String type, String url, Integer to, LocalDateTime startedTime, LocalDateTime createTime, LocalDateTime updateTime, LocalDateTime finishedTime) {
        super(Project.PROJECT);

        set(0, id);
        set(1, userId);
        set(2, name);
        set(3, contents);
        set(4, viewCount);
        set(5, thumbnail);
        set(6, description);
        set(7, authority);
        set(8, total);
        set(9, type);
        set(10, url);
        set(11, to);
        set(12, startedTime);
        set(13, createTime);
        set(14, updateTime);
        set(15, finishedTime);
    }
}
