/*
 * This file is generated by jOOQ.
 */
package com.ymm.back.domain.tables.records;


import com.ymm.back.domain.tables.Project;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProjectRecord extends UpdatableRecordImpl<ProjectRecord> implements Record11<Integer, String, String, Integer, String, String, String, String, String, Integer, String> {

    private static final long serialVersionUID = 602243806;

    /**
     * Setter for <code>hwant.project.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>hwant.project.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>hwant.project.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>hwant.project.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>hwant.project.contents</code>.
     */
    public void setContents(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>hwant.project.contents</code>.
     */
    public String getContents() {
        return (String) get(2);
    }

    /**
     * Setter for <code>hwant.project.view_count</code>.
     */
    public void setViewCount(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>hwant.project.view_count</code>.
     */
    public Integer getViewCount() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>hwant.project.thumbnail</code>.
     */
    public void setThumbnail(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>hwant.project.thumbnail</code>.
     */
    public String getThumbnail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>hwant.project.description</code>.
     */
    public void setDescription(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>hwant.project.description</code>.
     */
    public String getDescription() {
        return (String) get(5);
    }

    /**
     * Setter for <code>hwant.project.created_at</code>.
     */
    public void setCreatedAt(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>hwant.project.created_at</code>.
     */
    public String getCreatedAt() {
        return (String) get(6);
    }

    /**
     * Setter for <code>hwant.project.updated_at</code>.
     */
    public void setUpdatedAt(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>hwant.project.updated_at</code>.
     */
    public String getUpdatedAt() {
        return (String) get(7);
    }

    /**
     * Setter for <code>hwant.project.finished_at</code>.
     */
    public void setFinishedAt(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>hwant.project.finished_at</code>.
     */
    public String getFinishedAt() {
        return (String) get(8);
    }

    /**
     * Setter for <code>hwant.project.user_fk</code>.
     */
    public void setUserFk(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>hwant.project.user_fk</code>.
     */
    public Integer getUserFk() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>hwant.project.authority</code>.
     */
    public void setAuthority(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>hwant.project.authority</code>.
     */
    public String getAuthority() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<Integer, String, String, Integer, String, String, String, String, String, Integer, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<Integer, String, String, Integer, String, String, String, String, String, Integer, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Project.PROJECT.ID;
    }

    @Override
    public Field<String> field2() {
        return Project.PROJECT.NAME;
    }

    @Override
    public Field<String> field3() {
        return Project.PROJECT.CONTENTS;
    }

    @Override
    public Field<Integer> field4() {
        return Project.PROJECT.VIEW_COUNT;
    }

    @Override
    public Field<String> field5() {
        return Project.PROJECT.THUMBNAIL;
    }

    @Override
    public Field<String> field6() {
        return Project.PROJECT.DESCRIPTION;
    }

    @Override
    public Field<String> field7() {
        return Project.PROJECT.CREATED_AT;
    }

    @Override
    public Field<String> field8() {
        return Project.PROJECT.UPDATED_AT;
    }

    @Override
    public Field<String> field9() {
        return Project.PROJECT.FINISHED_AT;
    }

    @Override
    public Field<Integer> field10() {
        return Project.PROJECT.USER_FK;
    }

    @Override
    public Field<String> field11() {
        return Project.PROJECT.AUTHORITY;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getContents();
    }

    @Override
    public Integer component4() {
        return getViewCount();
    }

    @Override
    public String component5() {
        return getThumbnail();
    }

    @Override
    public String component6() {
        return getDescription();
    }

    @Override
    public String component7() {
        return getCreatedAt();
    }

    @Override
    public String component8() {
        return getUpdatedAt();
    }

    @Override
    public String component9() {
        return getFinishedAt();
    }

    @Override
    public Integer component10() {
        return getUserFk();
    }

    @Override
    public String component11() {
        return getAuthority();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getContents();
    }

    @Override
    public Integer value4() {
        return getViewCount();
    }

    @Override
    public String value5() {
        return getThumbnail();
    }

    @Override
    public String value6() {
        return getDescription();
    }

    @Override
    public String value7() {
        return getCreatedAt();
    }

    @Override
    public String value8() {
        return getUpdatedAt();
    }

    @Override
    public String value9() {
        return getFinishedAt();
    }

    @Override
    public Integer value10() {
        return getUserFk();
    }

    @Override
    public String value11() {
        return getAuthority();
    }

    @Override
    public ProjectRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ProjectRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ProjectRecord value3(String value) {
        setContents(value);
        return this;
    }

    @Override
    public ProjectRecord value4(Integer value) {
        setViewCount(value);
        return this;
    }

    @Override
    public ProjectRecord value5(String value) {
        setThumbnail(value);
        return this;
    }

    @Override
    public ProjectRecord value6(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public ProjectRecord value7(String value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public ProjectRecord value8(String value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public ProjectRecord value9(String value) {
        setFinishedAt(value);
        return this;
    }

    @Override
    public ProjectRecord value10(Integer value) {
        setUserFk(value);
        return this;
    }

    @Override
    public ProjectRecord value11(String value) {
        setAuthority(value);
        return this;
    }

    @Override
    public ProjectRecord values(Integer value1, String value2, String value3, Integer value4, String value5, String value6, String value7, String value8, String value9, Integer value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjectRecord
     */
    public ProjectRecord() {
        super(Project.PROJECT);
    }

    /**
     * Create a detached, initialised ProjectRecord
     */
    public ProjectRecord(Integer id, String name, String contents, Integer viewCount, String thumbnail, String description, String createdAt, String updatedAt, String finishedAt, Integer userFk, String authority) {
        super(Project.PROJECT);

        set(0, id);
        set(1, name);
        set(2, contents);
        set(3, viewCount);
        set(4, thumbnail);
        set(5, description);
        set(6, createdAt);
        set(7, updatedAt);
        set(8, finishedAt);
        set(9, userFk);
        set(10, authority);
    }
}
