/*
 * This file is generated by jOOQ.
 */
package com.ymm.back.domain.tables.records;


import com.ymm.back.domain.tables.User;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> implements Record10<Integer, String, String, String, String, String, String, LocalDateTime, LocalDateTime, String> {

    private static final long serialVersionUID = 919544841;

    /**
     * Setter for <code>douzone.user.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>douzone.user.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>douzone.user.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>douzone.user.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>douzone.user.email</code>.
     */
    public void setEmail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>douzone.user.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>douzone.user.password</code>.
     */
    public void setPassword(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>douzone.user.password</code>.
     */
    public String getPassword() {
        return (String) get(3);
    }

    /**
     * Setter for <code>douzone.user.tel</code>.
     */
    public void setTel(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>douzone.user.tel</code>.
     */
    public String getTel() {
        return (String) get(4);
    }

    /**
     * Setter for <code>douzone.user.profile</code>.
     */
    public void setProfile(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>douzone.user.profile</code>.
     */
    public String getProfile() {
        return (String) get(5);
    }

    /**
     * Setter for <code>douzone.user.job_title</code>.
     */
    public void setJobTitle(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>douzone.user.job_title</code>.
     */
    public String getJobTitle() {
        return (String) get(6);
    }

    /**
     * Setter for <code>douzone.user.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>douzone.user.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>douzone.user.update_time</code>.
     */
    public void setUpdateTime(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>douzone.user.update_time</code>.
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>douzone.user.ROLE</code>.
     */
    public void setRole(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>douzone.user.ROLE</code>.
     */
    public String getRole() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, String, String, String, String, String, String, LocalDateTime, LocalDateTime, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Integer, String, String, String, String, String, String, LocalDateTime, LocalDateTime, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return User.USER.ID;
    }

    @Override
    public Field<String> field2() {
        return User.USER.NAME;
    }

    @Override
    public Field<String> field3() {
        return User.USER.EMAIL;
    }

    @Override
    public Field<String> field4() {
        return User.USER.PASSWORD;
    }

    @Override
    public Field<String> field5() {
        return User.USER.TEL;
    }

    @Override
    public Field<String> field6() {
        return User.USER.PROFILE;
    }

    @Override
    public Field<String> field7() {
        return User.USER.JOB_TITLE;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return User.USER.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return User.USER.UPDATE_TIME;
    }

    @Override
    public Field<String> field10() {
        return User.USER.ROLE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getEmail();
    }

    @Override
    public String component4() {
        return getPassword();
    }

    @Override
    public String component5() {
        return getTel();
    }

    @Override
    public String component6() {
        return getProfile();
    }

    @Override
    public String component7() {
        return getJobTitle();
    }

    @Override
    public LocalDateTime component8() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component9() {
        return getUpdateTime();
    }

    @Override
    public String component10() {
        return getRole();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getEmail();
    }

    @Override
    public String value4() {
        return getPassword();
    }

    @Override
    public String value5() {
        return getTel();
    }

    @Override
    public String value6() {
        return getProfile();
    }

    @Override
    public String value7() {
        return getJobTitle();
    }

    @Override
    public LocalDateTime value8() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value9() {
        return getUpdateTime();
    }

    @Override
    public String value10() {
        return getRole();
    }

    @Override
    public UserRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public UserRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public UserRecord value3(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public UserRecord value4(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public UserRecord value5(String value) {
        setTel(value);
        return this;
    }

    @Override
    public UserRecord value6(String value) {
        setProfile(value);
        return this;
    }

    @Override
    public UserRecord value7(String value) {
        setJobTitle(value);
        return this;
    }

    @Override
    public UserRecord value8(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public UserRecord value9(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public UserRecord value10(String value) {
        setRole(value);
        return this;
    }

    @Override
    public UserRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, LocalDateTime value8, LocalDateTime value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(Integer id, String name, String email, String password, String tel, String profile, String jobTitle, LocalDateTime createTime, LocalDateTime updateTime, String role) {
        super(User.USER);

        set(0, id);
        set(1, name);
        set(2, email);
        set(3, password);
        set(4, tel);
        set(5, profile);
        set(6, jobTitle);
        set(7, createTime);
        set(8, updateTime);
        set(9, role);
    }
}
