/*
 * This file is generated by jOOQ.
 */
package com.ymm.back.domain.tables.records;


import com.ymm.back.domain.tables.User;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> implements Record15<Integer, String, String, String, String, String, String, String, String, String, Integer, String, String, String, String> {

    private static final long serialVersionUID = 756643861;

    /**
     * Setter for <code>hwant.user.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>hwant.user.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>hwant.user.u_name</code>.
     */
    public void setUName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>hwant.user.u_name</code>.
     */
    public String getUName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>hwant.user.email</code>.
     */
    public void setEmail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>hwant.user.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>hwant.user.password</code>.
     */
    public void setPassword(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>hwant.user.password</code>.
     */
    public String getPassword() {
        return (String) get(3);
    }

    /**
     * Setter for <code>hwant.user.wstoken</code>.
     */
    public void setWstoken(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>hwant.user.wstoken</code>.
     */
    public String getWstoken() {
        return (String) get(4);
    }

    /**
     * Setter for <code>hwant.user.jwt</code>.
     */
    public void setJwt(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>hwant.user.jwt</code>.
     */
    public String getJwt() {
        return (String) get(5);
    }

    /**
     * Setter for <code>hwant.user.tel</code>.
     */
    public void setTel(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>hwant.user.tel</code>.
     */
    public String getTel() {
        return (String) get(6);
    }

    /**
     * Setter for <code>hwant.user.created_at</code>.
     */
    public void setCreatedAt(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>hwant.user.created_at</code>.
     */
    public String getCreatedAt() {
        return (String) get(7);
    }

    /**
     * Setter for <code>hwant.user.updated_at</code>.
     */
    public void setUpdatedAt(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>hwant.user.updated_at</code>.
     */
    public String getUpdatedAt() {
        return (String) get(8);
    }

    /**
     * Setter for <code>hwant.user.profile</code>.
     */
    public void setProfile(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>hwant.user.profile</code>.
     */
    public String getProfile() {
        return (String) get(9);
    }

    /**
     * Setter for <code>hwant.user.role_id</code>.
     */
    public void setRoleId(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>hwant.user.role_id</code>.
     */
    public Integer getRoleId() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>hwant.user.credentials_non_expired</code>.
     */
    public void setCredentialsNonExpired(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>hwant.user.credentials_non_expired</code>.
     */
    public String getCredentialsNonExpired() {
        return (String) get(11);
    }

    /**
     * Setter for <code>hwant.user.account_non_locked</code>.
     */
    public void setAccountNonLocked(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>hwant.user.account_non_locked</code>.
     */
    public String getAccountNonLocked() {
        return (String) get(12);
    }

    /**
     * Setter for <code>hwant.user.account_non_expired</code>.
     */
    public void setAccountNonExpired(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>hwant.user.account_non_expired</code>.
     */
    public String getAccountNonExpired() {
        return (String) get(13);
    }

    /**
     * Setter for <code>hwant.user.enabled</code>.
     */
    public void setEnabled(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>hwant.user.enabled</code>.
     */
    public String getEnabled() {
        return (String) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row15<Integer, String, String, String, String, String, String, String, String, String, Integer, String, String, String, String> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    @Override
    public Row15<Integer, String, String, String, String, String, String, String, String, String, Integer, String, String, String, String> valuesRow() {
        return (Row15) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return User.USER.ID;
    }

    @Override
    public Field<String> field2() {
        return User.USER.U_NAME;
    }

    @Override
    public Field<String> field3() {
        return User.USER.EMAIL;
    }

    @Override
    public Field<String> field4() {
        return User.USER.PASSWORD;
    }

    @Override
    public Field<String> field5() {
        return User.USER.WSTOKEN;
    }

    @Override
    public Field<String> field6() {
        return User.USER.JWT;
    }

    @Override
    public Field<String> field7() {
        return User.USER.TEL;
    }

    @Override
    public Field<String> field8() {
        return User.USER.CREATED_AT;
    }

    @Override
    public Field<String> field9() {
        return User.USER.UPDATED_AT;
    }

    @Override
    public Field<String> field10() {
        return User.USER.PROFILE;
    }

    @Override
    public Field<Integer> field11() {
        return User.USER.ROLE_ID;
    }

    @Override
    public Field<String> field12() {
        return User.USER.CREDENTIALS_NON_EXPIRED;
    }

    @Override
    public Field<String> field13() {
        return User.USER.ACCOUNT_NON_LOCKED;
    }

    @Override
    public Field<String> field14() {
        return User.USER.ACCOUNT_NON_EXPIRED;
    }

    @Override
    public Field<String> field15() {
        return User.USER.ENABLED;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUName();
    }

    @Override
    public String component3() {
        return getEmail();
    }

    @Override
    public String component4() {
        return getPassword();
    }

    @Override
    public String component5() {
        return getWstoken();
    }

    @Override
    public String component6() {
        return getJwt();
    }

    @Override
    public String component7() {
        return getTel();
    }

    @Override
    public String component8() {
        return getCreatedAt();
    }

    @Override
    public String component9() {
        return getUpdatedAt();
    }

    @Override
    public String component10() {
        return getProfile();
    }

    @Override
    public Integer component11() {
        return getRoleId();
    }

    @Override
    public String component12() {
        return getCredentialsNonExpired();
    }

    @Override
    public String component13() {
        return getAccountNonLocked();
    }

    @Override
    public String component14() {
        return getAccountNonExpired();
    }

    @Override
    public String component15() {
        return getEnabled();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUName();
    }

    @Override
    public String value3() {
        return getEmail();
    }

    @Override
    public String value4() {
        return getPassword();
    }

    @Override
    public String value5() {
        return getWstoken();
    }

    @Override
    public String value6() {
        return getJwt();
    }

    @Override
    public String value7() {
        return getTel();
    }

    @Override
    public String value8() {
        return getCreatedAt();
    }

    @Override
    public String value9() {
        return getUpdatedAt();
    }

    @Override
    public String value10() {
        return getProfile();
    }

    @Override
    public Integer value11() {
        return getRoleId();
    }

    @Override
    public String value12() {
        return getCredentialsNonExpired();
    }

    @Override
    public String value13() {
        return getAccountNonLocked();
    }

    @Override
    public String value14() {
        return getAccountNonExpired();
    }

    @Override
    public String value15() {
        return getEnabled();
    }

    @Override
    public UserRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public UserRecord value2(String value) {
        setUName(value);
        return this;
    }

    @Override
    public UserRecord value3(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public UserRecord value4(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public UserRecord value5(String value) {
        setWstoken(value);
        return this;
    }

    @Override
    public UserRecord value6(String value) {
        setJwt(value);
        return this;
    }

    @Override
    public UserRecord value7(String value) {
        setTel(value);
        return this;
    }

    @Override
    public UserRecord value8(String value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public UserRecord value9(String value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public UserRecord value10(String value) {
        setProfile(value);
        return this;
    }

    @Override
    public UserRecord value11(Integer value) {
        setRoleId(value);
        return this;
    }

    @Override
    public UserRecord value12(String value) {
        setCredentialsNonExpired(value);
        return this;
    }

    @Override
    public UserRecord value13(String value) {
        setAccountNonLocked(value);
        return this;
    }

    @Override
    public UserRecord value14(String value) {
        setAccountNonExpired(value);
        return this;
    }

    @Override
    public UserRecord value15(String value) {
        setEnabled(value);
        return this;
    }

    @Override
    public UserRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, Integer value11, String value12, String value13, String value14, String value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(Integer id, String uName, String email, String password, String wstoken, String jwt, String tel, String createdAt, String updatedAt, String profile, Integer roleId, String credentialsNonExpired, String accountNonLocked, String accountNonExpired, String enabled) {
        super(User.USER);

        set(0, id);
        set(1, uName);
        set(2, email);
        set(3, password);
        set(4, wstoken);
        set(5, jwt);
        set(6, tel);
        set(7, createdAt);
        set(8, updatedAt);
        set(9, profile);
        set(10, roleId);
        set(11, credentialsNonExpired);
        set(12, accountNonLocked);
        set(13, accountNonExpired);
        set(14, enabled);
    }
}
