/*
 * This file is generated by jOOQ.
 */
package com.ymm.back.domain.tables.records;


import com.ymm.back.domain.tables.Voting;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VotingRecord extends UpdatableRecordImpl<VotingRecord> implements Record6<Integer, Integer, Integer, LocalDateTime, LocalDateTime, String> {

    private static final long serialVersionUID = 2757301;

    /**
     * Setter for <code>voting.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>voting.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>voting.agenda_id</code>.
     */
    public void setAgendaId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>voting.agenda_id</code>.
     */
    public Integer getAgendaId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>voting.member_id</code>.
     */
    public void setMemberId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>voting.member_id</code>.
     */
    public Integer getMemberId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>voting.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>voting.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>voting.update_time</code>.
     */
    public void setUpdateTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>voting.update_time</code>.
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>voting.choice</code>.
     */
    public void setChoice(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>voting.choice</code>.
     */
    public String getChoice() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Integer, Integer, LocalDateTime, LocalDateTime, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, Integer, Integer, LocalDateTime, LocalDateTime, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Voting.VOTING.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Voting.VOTING.AGENDA_ID;
    }

    @Override
    public Field<Integer> field3() {
        return Voting.VOTING.MEMBER_ID;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Voting.VOTING.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Voting.VOTING.UPDATE_TIME;
    }

    @Override
    public Field<String> field6() {
        return Voting.VOTING.CHOICE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getAgendaId();
    }

    @Override
    public Integer component3() {
        return getMemberId();
    }

    @Override
    public LocalDateTime component4() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component5() {
        return getUpdateTime();
    }

    @Override
    public String component6() {
        return getChoice();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getAgendaId();
    }

    @Override
    public Integer value3() {
        return getMemberId();
    }

    @Override
    public LocalDateTime value4() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value5() {
        return getUpdateTime();
    }

    @Override
    public String value6() {
        return getChoice();
    }

    @Override
    public VotingRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public VotingRecord value2(Integer value) {
        setAgendaId(value);
        return this;
    }

    @Override
    public VotingRecord value3(Integer value) {
        setMemberId(value);
        return this;
    }

    @Override
    public VotingRecord value4(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public VotingRecord value5(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public VotingRecord value6(String value) {
        setChoice(value);
        return this;
    }

    @Override
    public VotingRecord values(Integer value1, Integer value2, Integer value3, LocalDateTime value4, LocalDateTime value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VotingRecord
     */
    public VotingRecord() {
        super(Voting.VOTING);
    }

    /**
     * Create a detached, initialised VotingRecord
     */
    public VotingRecord(Integer id, Integer agendaId, Integer memberId, LocalDateTime createTime, LocalDateTime updateTime, String choice) {
        super(Voting.VOTING);

        set(0, id);
        set(1, agendaId);
        set(2, memberId);
        set(3, createTime);
        set(4, updateTime);
        set(5, choice);
    }
}
