/*
 * This file is generated by jOOQ.
 */
package com.ymm.back.domain.tables.records;


import com.ymm.back.domain.tables.Work;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WorkRecord extends UpdatableRecordImpl<WorkRecord> implements Record12<Integer, Integer, Integer, String, String, String, String, String, LocalDateTime, LocalDateTime, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = -2025797824;

    /**
     * Setter for <code>work.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>work.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>work.project_id</code>.
     */
    public void setProjectId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>work.project_id</code>.
     */
    public Integer getProjectId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>work.member_id</code>.
     */
    public void setMemberId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>work.member_id</code>.
     */
    public Integer getMemberId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>work.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>work.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>work.status</code>.
     */
    public void setStatus(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>work.status</code>.
     */
    public String getStatus() {
        return (String) get(4);
    }

    /**
     * Setter for <code>work.color</code>.
     */
    public void setColor(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>work.color</code>.
     */
    public String getColor() {
        return (String) get(5);
    }

    /**
     * Setter for <code>work.description</code>.
     */
    public void setDescription(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>work.description</code>.
     */
    public String getDescription() {
        return (String) get(6);
    }

    /**
     * Setter for <code>work.hashtag</code>.
     */
    public void setHashtag(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>work.hashtag</code>.
     */
    public String getHashtag() {
        return (String) get(7);
    }

    /**
     * Setter for <code>work.started_at</code>.
     */
    public void setStartedAt(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>work.started_at</code>.
     */
    public LocalDateTime getStartedAt() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>work.finished_at</code>.
     */
    public void setFinishedAt(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>work.finished_at</code>.
     */
    public LocalDateTime getFinishedAt() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>work.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>work.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>work.update_time</code>.
     */
    public void setUpdateTime(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>work.update_time</code>.
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<Integer, Integer, Integer, String, String, String, String, String, LocalDateTime, LocalDateTime, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<Integer, Integer, Integer, String, String, String, String, String, LocalDateTime, LocalDateTime, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Work.WORK.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Work.WORK.PROJECT_ID;
    }

    @Override
    public Field<Integer> field3() {
        return Work.WORK.MEMBER_ID;
    }

    @Override
    public Field<String> field4() {
        return Work.WORK.NAME;
    }

    @Override
    public Field<String> field5() {
        return Work.WORK.STATUS;
    }

    @Override
    public Field<String> field6() {
        return Work.WORK.COLOR;
    }

    @Override
    public Field<String> field7() {
        return Work.WORK.DESCRIPTION;
    }

    @Override
    public Field<String> field8() {
        return Work.WORK.HASHTAG;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return Work.WORK.STARTED_AT;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return Work.WORK.FINISHED_AT;
    }

    @Override
    public Field<LocalDateTime> field11() {
        return Work.WORK.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return Work.WORK.UPDATE_TIME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getProjectId();
    }

    @Override
    public Integer component3() {
        return getMemberId();
    }

    @Override
    public String component4() {
        return getName();
    }

    @Override
    public String component5() {
        return getStatus();
    }

    @Override
    public String component6() {
        return getColor();
    }

    @Override
    public String component7() {
        return getDescription();
    }

    @Override
    public String component8() {
        return getHashtag();
    }

    @Override
    public LocalDateTime component9() {
        return getStartedAt();
    }

    @Override
    public LocalDateTime component10() {
        return getFinishedAt();
    }

    @Override
    public LocalDateTime component11() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component12() {
        return getUpdateTime();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getProjectId();
    }

    @Override
    public Integer value3() {
        return getMemberId();
    }

    @Override
    public String value4() {
        return getName();
    }

    @Override
    public String value5() {
        return getStatus();
    }

    @Override
    public String value6() {
        return getColor();
    }

    @Override
    public String value7() {
        return getDescription();
    }

    @Override
    public String value8() {
        return getHashtag();
    }

    @Override
    public LocalDateTime value9() {
        return getStartedAt();
    }

    @Override
    public LocalDateTime value10() {
        return getFinishedAt();
    }

    @Override
    public LocalDateTime value11() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value12() {
        return getUpdateTime();
    }

    @Override
    public WorkRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public WorkRecord value2(Integer value) {
        setProjectId(value);
        return this;
    }

    @Override
    public WorkRecord value3(Integer value) {
        setMemberId(value);
        return this;
    }

    @Override
    public WorkRecord value4(String value) {
        setName(value);
        return this;
    }

    @Override
    public WorkRecord value5(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public WorkRecord value6(String value) {
        setColor(value);
        return this;
    }

    @Override
    public WorkRecord value7(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public WorkRecord value8(String value) {
        setHashtag(value);
        return this;
    }

    @Override
    public WorkRecord value9(LocalDateTime value) {
        setStartedAt(value);
        return this;
    }

    @Override
    public WorkRecord value10(LocalDateTime value) {
        setFinishedAt(value);
        return this;
    }

    @Override
    public WorkRecord value11(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public WorkRecord value12(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public WorkRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5, String value6, String value7, String value8, LocalDateTime value9, LocalDateTime value10, LocalDateTime value11, LocalDateTime value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WorkRecord
     */
    public WorkRecord() {
        super(Work.WORK);
    }

    /**
     * Create a detached, initialised WorkRecord
     */
    public WorkRecord(Integer id, Integer projectId, Integer memberId, String name, String status, String color, String description, String hashtag, LocalDateTime startedAt, LocalDateTime finishedAt, LocalDateTime createTime, LocalDateTime updateTime) {
        super(Work.WORK);

        set(0, id);
        set(1, projectId);
        set(2, memberId);
        set(3, name);
        set(4, status);
        set(5, color);
        set(6, description);
        set(7, hashtag);
        set(8, startedAt);
        set(9, finishedAt);
        set(10, createTime);
        set(11, updateTime);
    }
}
