/*
 * This file is generated by jOOQ.
 */
package com.ymm.back.domain;


import com.ymm.back.domain.tables.Agenda;
import com.ymm.back.domain.tables.Comment;
import com.ymm.back.domain.tables.Databasechangelog;
import com.ymm.back.domain.tables.Databasechangeloglock;
import com.ymm.back.domain.tables.FileStorage;
import com.ymm.back.domain.tables.Hashtag;
import com.ymm.back.domain.tables.Member;
import com.ymm.back.domain.tables.Message;
import com.ymm.back.domain.tables.Project;
import com.ymm.back.domain.tables.User;
import com.ymm.back.domain.tables.Voting;
import com.ymm.back.domain.tables.Work;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Douzone extends SchemaImpl {

    private static final long serialVersionUID = 361285559;

    /**
     * The reference instance of <code>douzone</code>
     */
    public static final Douzone DOUZONE = new Douzone();

    /**
     * The table <code>douzone.agenda</code>.
     */
    public final Agenda AGENDA = Agenda.AGENDA;

    /**
     * The table <code>douzone.comment</code>.
     */
    public final Comment COMMENT = Comment.COMMENT;

    /**
     * The table <code>douzone.databasechangelog</code>.
     */
    public final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>douzone.databasechangeloglock</code>.
     */
    public final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>douzone.file_storage</code>.
     */
    public final FileStorage FILE_STORAGE = FileStorage.FILE_STORAGE;

    /**
     * The table <code>douzone.hashtag</code>.
     */
    public final Hashtag HASHTAG = Hashtag.HASHTAG;

    /**
     * The table <code>douzone.member</code>.
     */
    public final Member MEMBER = Member.MEMBER;

    /**
     * The table <code>douzone.message</code>.
     */
    public final Message MESSAGE = Message.MESSAGE;

    /**
     * The table <code>douzone.project</code>.
     */
    public final Project PROJECT = Project.PROJECT;

    /**
     * The table <code>douzone.user</code>.
     */
    public final User USER = User.USER;

    /**
     * The table <code>douzone.voting</code>.
     */
    public final Voting VOTING = Voting.VOTING;

    /**
     * The table <code>douzone.work</code>.
     */
    public final Work WORK = Work.WORK;

    /**
     * No further instances allowed
     */
    private Douzone() {
        super("douzone", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Agenda.AGENDA,
            Comment.COMMENT,
            Databasechangelog.DATABASECHANGELOG,
            Databasechangeloglock.DATABASECHANGELOGLOCK,
            FileStorage.FILE_STORAGE,
            Hashtag.HASHTAG,
            Member.MEMBER,
            Message.MESSAGE,
            Project.PROJECT,
            User.USER,
            Voting.VOTING,
            Work.WORK);
    }
}
