/*
 * This file is generated by jOOQ.
 */
package com.ymm.back.domain;


import com.ymm.back.domain.tables.Databasechangelog;
import com.ymm.back.domain.tables.Databasechangeloglock;
import com.ymm.back.domain.tables.FileStorage;
import com.ymm.back.domain.tables.Message;
import com.ymm.back.domain.tables.Project;
import com.ymm.back.domain.tables.ProjectMember;
import com.ymm.back.domain.tables.User;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Hwant extends SchemaImpl {

    private static final long serialVersionUID = -2142912372;

    /**
     * The reference instance of <code>hwant</code>
     */
    public static final Hwant HWANT = new Hwant();

    /**
     * The table <code>hwant.DATABASECHANGELOG</code>.
     */
    public final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>hwant.DATABASECHANGELOGLOCK</code>.
     */
    public final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>hwant.file_storage</code>.
     */
    public final FileStorage FILE_STORAGE = FileStorage.FILE_STORAGE;

    /**
     * The table <code>hwant.message</code>.
     */
    public final Message MESSAGE = Message.MESSAGE;

    /**
     * The table <code>hwant.project</code>.
     */
    public final Project PROJECT = Project.PROJECT;

    /**
     * The table <code>hwant.project_member</code>.
     */
    public final ProjectMember PROJECT_MEMBER = ProjectMember.PROJECT_MEMBER;

    /**
     * The table <code>hwant.user</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private Hwant() {
        super("hwant", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Databasechangelog.DATABASECHANGELOG,
            Databasechangeloglock.DATABASECHANGELOGLOCK,
            FileStorage.FILE_STORAGE,
            Message.MESSAGE,
            Project.PROJECT,
            ProjectMember.PROJECT_MEMBER,
            User.USER);
    }
}
