/*
 * This file is generated by jOOQ.
 */
package com.ymm.back.domain;


import com.ymm.back.domain.tables.Agenda;
import com.ymm.back.domain.tables.Comment;
import com.ymm.back.domain.tables.Databasechangelog;
import com.ymm.back.domain.tables.Databasechangeloglock;
import com.ymm.back.domain.tables.FileStorage;
import com.ymm.back.domain.tables.Hashtag;
import com.ymm.back.domain.tables.Message;
import com.ymm.back.domain.tables.Project;
import com.ymm.back.domain.tables.ProjectMember;
import com.ymm.back.domain.tables.User;
import com.ymm.back.domain.tables.Voting;
import com.ymm.back.domain.tables.Work;


/**
 * Convenience access to all tables in 
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>agenda</code>.
     */
    public static final Agenda AGENDA = Agenda.AGENDA;

    /**
     * The table <code>comment</code>.
     */
    public static final Comment COMMENT = Comment.COMMENT;

    /**
     * The table <code>databasechangelog</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>databasechangeloglock</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>file_storage</code>.
     */
    public static final FileStorage FILE_STORAGE = FileStorage.FILE_STORAGE;

    /**
     * The table <code>hashtag</code>.
     */
    public static final Hashtag HASHTAG = Hashtag.HASHTAG;

    /**
     * The table <code>message</code>.
     */
    public static final Message MESSAGE = Message.MESSAGE;

    /**
     * The table <code>project</code>.
     */
    public static final Project PROJECT = Project.PROJECT;

    /**
     * The table <code>project_member</code>.
     */
    public static final ProjectMember PROJECT_MEMBER = ProjectMember.PROJECT_MEMBER;

    /**
     * The table <code>user</code>.
     */
    public static final User USER = User.USER;

    /**
     * The table <code>voting</code>.
     */
    public static final Voting VOTING = Voting.VOTING;

    /**
     * The table <code>work</code>.
     */
    public static final Work WORK = Work.WORK;
}
